DECLARE
	/*GER_PESSOA*/ 
		@PES_NOME VARCHAR(200), @PES_DATA_CADASTRO DATETIME, @PES_TIPO CHAR(1), @PES_CPF_CNPJ VARCHAR(14),
		@PES_ORGAO_EXPEDIDOR VARCHAR(20), @PES_DATA_EXPEDICAO DATETIME, @PES_DATA_NASCIMENTO DATETIME,
		@PES_OBSERVACAO VARCHAR(MAX), @IEC_CODIGO INT, @PES_PROFISSAO VARCHAR(45), @PES_SEXO CHAR(1),
		@PES_NATURALIDADE VARCHAR(50), @PES_NACIONALIDADE VARCHAR(50), @PES_EMAIL VARCHAR(50), @PES_RG VARCHAR(20),
		@PES_NOME_FANTASIA VARCHAR(200), @PES_COD_OLD BIGINT, @PES_DATA_MIGRACAO DATETIME,
	/* GER_ENDERECO */
		@END_CEP VARCHAR(8), @END_ENDERECO VARCHAR(200), @END_UF VARCHAR(2), @END_CIDADE VARCHAR(200),
		@END_BAIRRO VARCHAR(50), @END_TELEFONE VARCHAR(20), @END_COMPLEMENTO VARCHAR(50), @END_COD_OLD INT, @END_NUMERO VARCHAR(10),
		@END_TIPO CHAR(1)

DECLARE CURSO_PADRAO CURSOR FOR
/*==========================================================================================*/
SELECT DISTINCT
/* GER_PESSOA */
nm_pessoa PES_NOME,
GETDATE() PES_DATA_CADASTRO,
p.ie_pessoa PES_TIPO,
NULLIF(p.tx_documento, '') PES_CPF_CNPJ,
NULLIF(p.tx_orgao_expedidor, '') PES_ORGAO_EXPEDIDOR,
NULLIF(p.dt_expedicao, '') PES_DATA_EXPEDICAO,
p.dt_nascimento PES_DATA_NASCIMENTO,
NULLIF(p.tx_observacao, '') PES_OBSERVACAO,
p.st_civil,
Case 
	When p.st_civil = 'C' Then '2233'
	When p.st_civil = 'S' Then '2234'
	When p.st_civil = 'D' Then '2235'
	When p.st_civil = 'V' Then '2236'
	Else NULL
End IEC_CODIGO,
NULLIF(p.tx_profissao, '') PES_PROFISSAO,
NULLIF(p.ie_sexo, '') PES_SEXO,
NULLIF(pc.tx_naturalidade, '')  PES_NATURALIDADE,
NULLIF(UPPER(pc.tx_pais_nacionalidade), '')  PES_NACIONALIDADE,
NULLIF(p.tx_email, '') PES_EMAIL,
NULLIF(p.tx_rg, '') PES_RG,
NULLIF(pc.nm_fantasia, '') PES_NOME_FANTASIA,
p.id_pessoa PES_COD_OLD,
GETDATE() PES_DATA_MIGRACAO,
/* GER_ENDERECO */
NULLIF(e.tx_cep, '') END_CEP,
NULLIF(UPPER(e.ds_endereco), '') END_ENDERECO,
NULLIF(e.sg_uf, '') END_UF,
NULLIF(UPPER(e.ds_cidade), '') END_CIDADE,
NULLIF(UPPER(e.ds_bairro), '') END_BAIRRO,
NULLIF(REPLACE(REPLACE(REPLACE(REPLACE(p.tx_telefone, '(', ''), ')', ''), '-', ''), ' ', ''), '') END_TELEFONE,
NULLIF(UPPER(e.ds_endereco_complemento), '') END_COMPLEMENTO,
e.id_endereco END_COD_OLD,
NULLIF(e.nr_endereco, '') ENDP_NUMERO,
'R' END_TIPO
FROM
SAPEACU_GERAL..cg_pessoa p
left join SAPEACU_GERAL..cg_pessoa_complemento pc on p.fk_id_pessoa_complemento = pc.id_pessoa_complemento
left join SAPEACU_GERAL..cg_endereco e on p.fk_id_endereco = e.id_endereco

/*==========================================================================================*/


OPEN CURSO_PADRAO
 FETCH NEXT FROM CURSO_PADRAO INTO

 /* VARIÁVEIS DO USUÁRIO UTILIZADAS */
	/* GER_PESSOA */
		@PES_NOME, @PES_DATA_CADASTRO, @PES_TIPO, @PES_CPF_CNPJ,
		@PES_ORGAO_EXPEDIDOR, @PES_DATA_EXPEDICAO, @PES_DATA_NASCIMENTO,
		@PES_OBSERVACAO, @IEC_CODIGO, @PES_PROFISSAO, @PES_SEXO,
		@PES_NATURALIDADE, @PES_NACIONALIDADE, @PES_EMAIL, @PES_RG,
		@PES_NOME_FANTASIA, @PES_COD_OLD, @PES_DATA_MIGRACAO,
	/* GER_ENDERECO */
		@END_CEP, @END_ENDERECO, @END_UF, @END_CIDADE,
		@END_BAIRRO, @END_TELEFONE, @END_COMPLEMENTO, @END_COD_OLD, @END_NUMERO,
		@END_TIPO

 WHILE @@FETCH_STATUS = 0
 BEGIN
/*==========================================================================================*/
		DECLARE @ENTIDADE INT
		SET @ENTIDADE = 1076
/*==========================================================================================*/

		 /*GER_PESSOA*/
		  INSERT INTO IMOVEIS..GER_PESSOA
		 (PES_NOME, PES_DATA_CADASTRO, PES_TIPO, PES_CPF_CNPJ,
		PES_ORGAO_EXPEDIDOR, PES_DATA_EXPEDICAO, PES_DATA_NASCIMENTO,
		PES_OBSERVACAO, IEC_CODIGO, PES_PROFISSAO, PES_SEXO,
		PES_NATURALIDADE, PES_NACIONALIDADE, PES_EMAIL, PES_RG,
		PES_NOME_FANTASIA, PES_COD_OLD, PES_DATA_MIGRACAO, ENT_CODIGO)
		 VALUES
		 (@PES_NOME, @PES_DATA_CADASTRO, @PES_TIPO, @PES_CPF_CNPJ,
		@PES_ORGAO_EXPEDIDOR, @PES_DATA_EXPEDICAO, @PES_DATA_NASCIMENTO,
		@PES_OBSERVACAO, @IEC_CODIGO, @PES_PROFISSAO, @PES_SEXO,
		@PES_NATURALIDADE, @PES_NACIONALIDADE, @PES_EMAIL, @PES_RG,
		@PES_NOME_FANTASIA, @PES_COD_OLD, @PES_DATA_MIGRACAO, @ENTIDADE)

		 DECLARE @LAST_ID AS INT
		 SET @LAST_ID = SCOPE_IDENTITY()

		 /* GER_ENDERECO */  
		INSERT INTO IMOVEIS..GER_ENDERECO
		(END_CEP, END_ENDERECO, END_UF, END_CIDADE,
		END_BAIRRO, END_TELEFONE, END_COMPLEMENTO, END_COD_OLD, END_NUMERO, END_TIPO, PES_COD)
		VALUES
		(@END_CEP, @END_ENDERECO, @END_UF, @END_CIDADE,
		@END_BAIRRO, @END_TELEFONE, @END_COMPLEMENTO, @END_COD_OLD, @END_NUMERO, @END_TIPO, @LAST_ID)


	 FETCH NEXT FROM CURSO_PADRAO INTO
	/* VARIÁVEIS DO USUÁRIO UTILIZADAS, DITAS NO OPEN */
	/*GER_PESSOA*/
		@PES_NOME, @PES_DATA_CADASTRO, @PES_TIPO, @PES_CPF_CNPJ,
		@PES_ORGAO_EXPEDIDOR, @PES_DATA_EXPEDICAO, @PES_DATA_NASCIMENTO,
		@PES_OBSERVACAO, @IEC_CODIGO, @PES_PROFISSAO, @PES_SEXO,
		@PES_NATURALIDADE, @PES_NACIONALIDADE, @PES_EMAIL, @PES_RG,
		@PES_NOME_FANTASIA, @PES_COD_OLD, @PES_DATA_MIGRACAO,
	/*GER_END_PESSOA*/
		@END_CEP, @END_ENDERECO, @END_UF, @END_CIDADE,
		@END_BAIRRO, @END_TELEFONE, @END_COMPLEMENTO, @END_COD_OLD, @END_NUMERO,
		@END_TIPO

END

CLOSE CURSO_PADRAO
DEALLOCATE CURSO_PADRAO
