DECLARE
	/* PRO_DAJE */
	@DAJ_DATA_EMI DATETIME, @DAJ_DATA_VENC DATETIME, @DAJ_DATA_PG DATETIME, @DAJ_COD_ATO VARCHAR(10), @DAJ_EMOL_DAJE NUMERIC(16,2),
	@DAJ_TAXA_FISICALIZACAO NUMERIC(16,2), @DAJ_FECOM NUMERIC(16,2), @DAJ_DEFEN_PUBLIC NUMERIC(16,2), @DAJ_VR_VALOR NUMERIC(16,2),
	@DAJ_QTD INT, @DAJ_USUARIO INT, @PES_COD_CONTRIBUINTE INT, @DAJ_SERIE VARCHAR(5), @DAJ_NUMERO VARCHAR(8), @DAJ_NUMERO_SELO VARCHAR(25),
	@DAJ_COD_VALIDACAO VARCHAR(25), @DAJ_VALOR_ATO NUMERIC(16,2), @DAJ_EMISSOR VARCHAR(5), @DAJ_PGE NUMERIC(16,2),
	@DAJ_FMMPBA NUMERIC(16,2), @DAJ_CODIGO_OLD VARCHAR(25), @DAJ_ISENTO INT, @DAJ_CODIGO_BARRA VARCHAR(200), @DAJ_SERIE_COMPLEMENTAR VARCHAR(5),
	@DAJ_NUM_COMPLEMENTAR VARCHAR(8), @DAJ_STATUS VARCHAR(25), @DAJ_BLOQUEADO VARCHAR(10) 

DECLARE CURSO_PADRAO CURSOR FOR

/*==========================================================================================*/
SELECT DISTINCT
/* PRO_DAJE */
d.dt_emissao DAJ_DATA_EMI,
d.dt_validade DAJ_DATA_VENC,
d.dt_pagamento DAJ_DATA_PG,
a.cd_ato DAJ_COD_ATO,
CAST(d.vl_emolumentos AS NUMERIC(16,2)) DAJ_EMOL_DAJE,
CAST(d.vl_fiscalizacao AS NUMERIC(16,2)) DAJ_TAXA_FISICALIZACAO,
CAST(d.vl_fecom AS NUMERIC(16,2)) DAJ_FECOM,
CAST(d.vl_defensoria AS NUMERIC(16,2)) DAJ_DEFEN_PUBLIC,
CAST(d.vl_daje AS NUMERIC(16,2)) DAJ_VR_VALOR,
1 DAJ_QTD,
NULL DAJ_USUARIO,
--(Select PES_COD from IMOVEIS..GER_PESSOA where PES_COD_OLD = d.fk_id_pessoa and ENT_CODIGO = 1076) PES_COD_CONTRIBUINTE,
d.nr_serie_daje DAJ_SERIE,
d.nr_daje DAJ_NUMERO,
REPLACE(REPLACE(s.tx_numero_selo, '.',''),'-','') DAJ_NUMERO_SELO,
s.tx_cd_validacao DAJ_COD_VALIDACAO,
CAST(NULLIF(d.vl_ato, '') AS NUMERIC(16,2)) DAJ_VALOR_ATO,
d.fk_cd_emissor DAJ_EMISSOR,
CAST(d.vl_pge AS NUMERIC(16,2)) DAJ_PGE,
CAST(NULLIF(d.vl_fmmpba, '') AS NUMERIC(16,2)) DAJ_FMMPBA,
CAST(CAST(d.id_daje AS BIGINT) AS VARCHAR(25)) DAJ_CODIGO_OLD,
IIF(d.is_isento = 't', 1, 0) DAJ_ISENTO,
d.cd_barra DAJ_CODIGO_BARRA,
Case
	When d.fk_id_daje_complementar is not null
	Then (Select nr_serie_daje from PALMEIRAS_GERAL..cg_daje where id_daje = d.fk_id_daje_complementar)
	Else NULL
	End DAJ_SERIE_COMPLEMENTAR,
Case
	When d.fk_id_daje_complementar is not null
	Then (Select nr_daje from PALMEIRAS_GERAL..cg_daje where id_daje = d.fk_id_daje_complementar)
	Else NULL
	End DAJ_NUM_COMPLEMENTAR,
Case
	When d.ie_daje_pago = 'T' Then 'Utilizado/Pago'
	When d.ie_daje_pago = 'N' Then 'Não Pago'
	When d.ie_daje_pago = 'P' Then 'Pago'
	When d.ie_daje_pago = 'U' Then 'Utilizado'
	When d.ie_daje_pago = 'I' Then 'Isento'
	Else NULL
	End DAJ_STATUS,
Case 
	When d.is_bloqueado = 'f' Then 'false'
	When d.is_bloqueado = '' Then 'false'
	Else NULL
	End DAJ_BLOQUEADO
FROM
SAPEACU_GERAL..cg_daje d 
left join SAPEACU_GERAL..cg_ato a on a.id_ato = d.fk_id_ato
left join SAPEACU_GERAL..cg_tipo_ato ta on ta.id_tipo_ato = a.fk_id_tipo_ato
left join SAPEACU_GERAL..cg_atribuicao at on a.fk_id_atribuicao = CAST(at.id_atribuicao AS VARCHAR(50))
left join SAPEACU_GERAL..cg_selo s on s.id_selo = d.fk_id_selo 
WHERE at.nm_atribuicao = 'RI'
ORDER BY a.cd_ato

/*==========================================================================================*/
OPEN CURSO_PADRAO
 FETCH NEXT FROM CURSO_PADRAO INTO
	/* PRO_DAJE */
	@DAJ_DATA_EMI, @DAJ_DATA_VENC, @DAJ_DATA_PG, @DAJ_COD_ATO, @DAJ_EMOL_DAJE,
	@DAJ_TAXA_FISICALIZACAO, @DAJ_FECOM, @DAJ_DEFEN_PUBLIC, @DAJ_VR_VALOR,
	@DAJ_QTD, @DAJ_USUARIO, @PES_COD_CONTRIBUINTE, @DAJ_SERIE, @DAJ_NUMERO, @DAJ_NUMERO_SELO,
	@DAJ_COD_VALIDACAO, @DAJ_VALOR_ATO, @DAJ_EMISSOR, @DAJ_PGE,
	@DAJ_FMMPBA, @DAJ_CODIGO_OLD, @DAJ_ISENTO, @DAJ_CODIGO_BARRA, @DAJ_SERIE_COMPLEMENTAR,
	@DAJ_NUM_COMPLEMENTAR, @DAJ_STATUS, @DAJ_BLOQUEADO
 WHILE @@FETCH_STATUS = 0
 BEGIN
 /*==========================================================================================*/
		DECLARE @ENTIDADE INT
		SET @ENTIDADE = 1076
/*==========================================================================================*/
	/* PRO_DAJE */
    INSERT INTO IMOVEIS..PRO_DAJE
	(DAJ_DATA_EMI,  DAJ_DATA_VENC,  DAJ_DATA_PG, DAJ_COD_ATO,  DAJ_EMOL_DAJE,
	 DAJ_TAXA_FISICALIZACAO,  DAJ_FECOM,  DAJ_DEFEN_PUBLIC,  DAJ_VR_VALOR,
	 DAJ_QTD,  DAJ_USUARIO,  PES_COD_CONTRIBUINTE,  DAJ_SERIE,  DAJ_NUMERO,  DAJ_NUMERO_SELO,
	 DAJ_COD_VALIDACAO,  DAJ_VALOR_ATO,  DAJ_EMISSOR,  DAJ_PGE,
	 DAJ_FMMPBA,  DAJ_CODIGO_OLD,  DAJ_ISENTO,  DAJ_CODIGO_BARRA,  DAJ_SERIE_COMPLEMENTAR,
	 DAJ_NUM_COMPLEMENTAR,  DAJ_STATUS,  DAJ_BLOQUEADO, ENT_CODIGO)
	VALUES
	(@DAJ_DATA_EMI, @DAJ_DATA_VENC, @DAJ_DATA_PG, @DAJ_COD_ATO, @DAJ_EMOL_DAJE,
	@DAJ_TAXA_FISICALIZACAO, @DAJ_FECOM, @DAJ_DEFEN_PUBLIC, @DAJ_VR_VALOR,
	@DAJ_QTD, @DAJ_USUARIO, @PES_COD_CONTRIBUINTE, @DAJ_SERIE, @DAJ_NUMERO, @DAJ_NUMERO_SELO,
	@DAJ_COD_VALIDACAO, @DAJ_VALOR_ATO, @DAJ_EMISSOR, @DAJ_PGE,
	@DAJ_FMMPBA, @DAJ_CODIGO_OLD, @DAJ_ISENTO, @DAJ_CODIGO_BARRA, @DAJ_SERIE_COMPLEMENTAR,
	@DAJ_NUM_COMPLEMENTAR, @DAJ_STATUS, @DAJ_BLOQUEADO, @ENTIDADE)
	     
       FETCH NEXT FROM CURSO_PADRAO INTO
	   /* PRO_DAJE */
	   @DAJ_DATA_EMI, @DAJ_DATA_VENC, @DAJ_DATA_PG, @DAJ_COD_ATO, @DAJ_EMOL_DAJE,
	@DAJ_TAXA_FISICALIZACAO, @DAJ_FECOM, @DAJ_DEFEN_PUBLIC, @DAJ_VR_VALOR,
	@DAJ_QTD, @DAJ_USUARIO, @PES_COD_CONTRIBUINTE, @DAJ_SERIE, @DAJ_NUMERO, @DAJ_NUMERO_SELO,
	@DAJ_COD_VALIDACAO, @DAJ_VALOR_ATO, @DAJ_EMISSOR, @DAJ_PGE,
	@DAJ_FMMPBA, @DAJ_CODIGO_OLD, @DAJ_ISENTO, @DAJ_CODIGO_BARRA, @DAJ_SERIE_COMPLEMENTAR,
	@DAJ_NUM_COMPLEMENTAR, @DAJ_STATUS, @DAJ_BLOQUEADO
 
END
CLOSE CURSO_PADRAO
DEALLOCATE CURSO_PADRAO 

	    
 